### PR TITLE
Ensure note windows close when app closes

### LINKED ISSUE #138: [PE-D][Tester A] Exiting the app does not close the note window
**Steps to reproduce**
1. Open a student's notes
2. Input 'exit'

**Expected**
Whole program to close

**Actual**
Only app closes, notes stay open

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Emberlynn-Loo/ped#8

### PR DESCRIPTION
**Pull request by gowthaman-01**
Fixes #138

### CODE REVIEW

**Review by AL-ZT — CHANGES_REQUESTED** [review]
Should this issue be counted towards "Enhancement"?

**Comment by gowthaman-01** [comment]
> Should this issue be counted towards "Enhancement"?

Nope, its a bug because the app is not properly cleaned up when exited.

**Review by AL-ZT — APPROVED** [review]
Fair enough, looks good.

**Comment by zoebelle-pang** [comment]
We should reconsider this issue, this issue might be counted towards enhancement instead since the note window offers an option to close/exit. While it may be inconvenient, it doesn't render the feature unusable.

**Pull request merged**
