### PR TITLE
Edit empty note console message

### LINKED ISSUE #151: [PE-D][Tester C] Notes in Edit Command Sequence Message Formatting can be improved
The error message when no note is added can be polished more, perhaps it can just say None, or not display the field if there is no note present since it is optional.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: theman-oj10/ped#8

### PR DESCRIPTION
**Pull request by gowthaman-01**
Fixes #151

### CODE REVIEW

**Comment by gowthaman-01** [comment]
> The issue targeted should be a feature flaw, therefore code changes shouldn't be allowed.

Hmm, but we are not exactly introducing a new feature right, its just a word change.

**Comment by Hwww23** [comment]
This is a feature flaw, it can be put under planned enhancement instead.

**Comment by AL-ZT** [comment]
> > The issue targeted should be a feature flaw, therefore code changes shouldn't be allowed.
> 
> Hmm, but we are not exactly introducing a new feature right, its just a word change.

I do feel like the line is a bit blurry, but it's been said that its not just about functional changes.

image

**Comment by gowthaman-01** [comment]
Oh right then its fine, we can close this.

**Pull request closed without merging**
